version: '3.8'  # Update this to the latest version

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend